### ISSUE TITLE
Why standalone?

### ISSUE THREAD

**Issue by patmarion** [openhumanoids/valkyrie-lcm-distro#9]
This appears to be a minimal distro for the link computer.  Why not maintain these files as part of oh-distro, and use software/externals to provide libbot and multisense driver, etc?  I built oh-distro on valkyrie and have been using things from software/build.  Do you guys foresee problems with that?  I guess adding oh-distro/software/build/lib to LD_LIBRARY_PATH adds a lot more libraries than this minimal valkyrie-lcm-distro.

**Comment by wxmerkt** [comment]
Short answer, we wanted the minimum amount possible to be installed/compiled on the robot. As a side effect, because it is so light-weight, we are using it for running Travis on valkyrie_translator.

[We didn't know it at the time but there are a couple libraries that have different versions (yaml-cpp e.g.), but that shouldn't be a problem since the packages that depend on them are not installed by default on link]

**Comment by patmarion** [comment]
Do you run pronto offboard?

We plan to start testing the QP controller offboard with the control commands sent to LCM2ROSController on link, but at some point in the future would like to investigate running onboard (using a full onboard build of oh-distro).

For Atlas, we use network filesystem sharing so that we only maintain a single onboard build, and the other onboard computers mount the oh-distro directory over NFS.

**Comment by wxmerkt** [comment]
We are currently not running pronto just yet online (there's some work on it off logs). @raluca-scona and @mauricefallon will know more details - I believe work on pronto will start soon-ish.
